export const TEST = 'test';
export const CLICK_SEARCH_BUTTON = 'CLICK_SEARCH_BUTTON';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const GET_IMAGES = 'GET_IMAGES';
export const EMPTY_AND_PAGE = 'EMPTY_PRODUCT_AND_PAGE';
export const CLICK_SEARCH_BUTTON_REFRESH = 'CLICK_SEARCH_BUTTON_REFRESH';
export const EMPTY_PRODUCT_LIST = 'EMPTY_PRODUCT_LIST';
export const CLICK_SEARCH_BUTTON_END = 'CLICK_SEARCH_BUTTON_END';
export const CLICK_SEARCH_NO_RESULT = 'CLICK_SEARCH_NO_RESULT';
export const ADD_TO_WISH = 'ADD_TO_WISH';
export const SORT_PRODUCT = 'SORT_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CUSTOMER_LEVEL = 'GET_CUSTOMER_LEVEL';
export const VIP_CLICK_ACTION = 'VIP_CLICK_ACTION';
export const CHANGE_PAGI = 'CHANGE_PAGI';
export const CHANGE_PRE_PAGI = 'CHANGE_PRE_PAGI';
export const CHANGE_SEARCH_PAGE = 'CHANGE_SEARCH_PAGE';


