export const SET_EMAIL_TO_LOGIN = 'SET_EMAIL_TO_LOGIN';
export const SET_PWD_TO_LOGIN = 'SET_PWD_TO_LOGIN';
export const SET_VERIFYCODE_TO_LOGIN = 'SET_VERIFYCODE_TO_LOGIN';
export const SET_VCODE_VALUE = 'SET_VCODE_VALUE';
export const LOGIN_SUCC = 'LOGIN_SUCC';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CODE_NOT_MATCH = 'CODE_NOT_MATCH';
export const RESET_VCODE_STATUS = 'RESET_VCODE_STATUS';
