export const TEST = 'test';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const CHANGE_INPUT_QUANTITY = 'CHANGE_INPUT_QUANTITY'
export const ADD_TO_CART = 'ADD_TO_CART'
export const EMPTY_QUANTITY_AND_DETAIL = 'EMPTY_QUANTITY_AND_DETAIL'
export const ADD_QUANTITY_1 = 'ADD_QUANTITY_1'
export const MINUS_QUANTITY_1 = 'MINUS_QUANTITY_1'
export const OUT_STOCK = 'OUT_STOCK';